### ISSUE TITLE
Bios print interupt

### ISSUE THREAD

**Issue by SheldonCompton** [SheldonCompton/ProgrammingClubGame#1]
For some reason when I run this on my computer it doesn't print the "ing" in "Loading".

**Comment by cooro** [comment]
Pray tell, to what code doth thou refereth? In each of thine commits, my eyes lie upon no "Load", nor "ing", nor "Loading". Bring light to mine inquirie at thine foremost convenience.
~Sudokuu the Enigmatic

**Comment by SheldonCompton** [comment]
BootLoader0.01 where it is going through and printing out the chars for "Loading".

**Comment by ghost** [comment]
It's the computer that tells you what do to, Shaldo...
