### ISSUE TITLE
cooro names his/her sound drivers after harmful substances

### ISSUE THREAD

**Issue by ghost** [SheldonCompton/ProgrammingClubGame#10]
![mastermind-g](https://cloud.githubusercontent.com/assets/10815401/19616983/7b01482e-97f1-11e6-85d1-a712d25ab84f.gif)

**Comment by cooro** [comment]
How is this an issue? I enjoy my name schemes

**Comment by ghost** [comment]
I felt like it.  _hmph_

**Comment by ghost** [comment]
cooro
