### ISSUE TITLE
LongMode.ASM is unable to compile properly...

### ISSUE THREAD

**Issue by ghost** [SheldonCompton/ProgrammingClubGame#4]
It's really just a simple syntactical error, so it should be an easy fix.

Just don't want to break the code, then have to rewrite the thing in its entirety.

**Comment by SheldonCompton** [comment]
Oh, come on I've put a good 20 hours in trying to get the bootloader to work.  We aren't copy and pasting now.

**Comment by ghost** [comment]
Okay, flat mode!
