### ISSUE TITLE
We need to find a bootloader to use.

### ISSUE THREAD

**Issue by SheldonCompton** [SheldonCompton/ProgrammingClubGame#5]

**Comment by ghost** [comment]
GRUB.

**Comment by ghost** [comment]
No bootloader is necessary for this software rasterizer.  Boot code, perhaps, but nothing so drastic as an entire bootloader.  I was thinking of making the entire binary and runtime pretty self-contained.

**Comment by ghost** [comment]
Also, C and GAS ASM are the best way to go for something such as this.
